<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pimpinan extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        is_login();
        $this->load->model('Info_keberangkatan_model');
        $this->load->model('Info_kepulangan_model');
        $this->load->model('Pimpinan_model');
        $this->load->library('form_validation');         
	$this->load->library('datatables');
    }

    public function index()
    {
        $this->template->load('template','pimpinan/pimpinan_list');
    } 
    
    public function json() {
        header('Content-Type: application/json');
        echo $this->Pimpinan_model->json1();
    }


    public function read($id) 
    {
        $row = $this->Pimpinan_model->get_by_id($id);
        if ($row) {
            $data = array(
                'id' => $row->id,
                'nama' => $row->nama,
                'tgl_keberangkatan' => $row->tgl_keberangkatan,
                'rute_keberangkatan' => $row->rute_keberangkatan,
                'tgl_kepulangan' => $row->tgl_kepulangan,
                'rute_kepulangan' => $row->rute_kepulangan,
            );
            $this->template->load('template','pimpinan/pimpinan_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('pimpinan'));
        }
    }
    
    
    public function create() 
    {
        $data = array(
            'button' => 'TAMBAH DATA PIMPINAN',
            'action' => site_url('pimpinan/create_action'),
            'id' => set_value('id'),
            'nama' => set_value('nama'),
            'tgl_keberangkatan' => set_value('tgl_keberangkatan'),
            'rute_keberangkatan' => set_value('rute_keberangkatan'),
            'tgl_kepulangan' => set_value('tgl_kepulangan'),
            'rute_kepulangan' => set_value('rute_kepulangan'),
        );
        $this->template->load('template','pimpinan/pimpinan_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
                'nama' => $this->input->post('nama',TRUE),
            );

            $this->Pimpinan_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success 2');
            redirect(site_url('pimpinan'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Pimpinan_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'UPDATE DATA PIMPINAN',
                'action' => site_url('pimpinan/update_action'),
                'id' => set_value('id', $row->id),
                'nama' => set_value('nama', $row->nama),
            );
            $this->template->load('template','pimpinan/pimpinan_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('pimpinan'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('id', TRUE));
        } else {
            $data = array(
                'nama' => $this->input->post('nama',TRUE),
            );

            $this->Pimpinan_model->update($this->input->post('id', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('pimpinan'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Pimpinan_model->get_by_id($id);

        if ($row) {
            $this->Pimpinan_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('pimpinan'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('pimpinan'));
        }
    }

    public function _rules() 
    {
        $this->form_validation->set_rules('nama', 'nama', 'trim|required');
        /*
        $this->form_validation->set_rules('tgl_keberangkatan', 'tgl keberangkatan', 'trim|required');
        $this->form_validation->set_rules('rute_keberangkatan', 'rute keberangkatan', 'trim|required');
        $this->form_validation->set_rules('tgl_kepulangan', 'tgl kepulangan', 'trim|required');
        $this->form_validation->set_rules('rute_kepulangan', 'rute kepulangan', 'trim|required');
        */
        $this->form_validation->set_rules('id', 'id', 'trim');
        $this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

    


}

/* End of file Pimpinan.php */
/* Location: ./application/controllers/Pimpinan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-09-14 07:53:15 */
/* http://harviacode.com */ 