<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Agenda_rapat_model extends CI_Model
{

    public $table = 'agenda_rapat';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id,tgl_rapat,tempat,pimpinan_rapat,waktu,agenda_rapat,keterangan');
        $this->datatables->from('agenda_rapat');
        //add this line for join
        //$this->datatables->join('table2', 'agenda_rapat.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('agenda_rapat/download/$1'),'<i class="fa fa-download" aria-hidden="true"></i>', array('class' => 'btn btn-warning btn-sm'))." 
            ".anchor(site_url('agenda_rapat/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-warning btn-sm'))." 
                ".anchor(site_url('agenda_rapat/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-warning btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();        
    }

    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('tgl_rapat', $q);
	$this->db->or_like('tempat', $q);
	$this->db->or_like('pimpinan_rapat', $q);
	$this->db->or_like('waktu', $q);
	$this->db->or_like('agenda_rapat', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('tgl_rapat', $q);
	$this->db->or_like('tempat', $q);
	$this->db->or_like('pimpinan_rapat', $q);
	$this->db->or_like('waktu', $q);
	$this->db->or_like('agenda_rapat', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
        return  $this->db->insert_id();
    }

    function insertfile($data)
    {
        $this->db->insert('lampiran_rapat', $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Agenda_rapat_model.php */
/* Location: ./application/models/Agenda_rapat_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-09-21 17:20:08 */
/* http://harviacode.com */