<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Agenda_surat_masuk_model extends CI_Model
{

    public $table = 'agenda_surat_masuk';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id,tgl_terima,tgl_surat,no_surat,pengirim,perihal,diteruskan_kpd,kode_arsip');
        $this->datatables->from('agenda_surat_masuk_view');
        //add this line for join
        //$this->datatables->join('table2', 'agenda_surat_masuk.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('agenda_surat_masuk/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-warning btn-sm'))." 
            ".anchor(site_url('agenda_surat_masuk/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-warning btn-sm'))." 
                ".anchor(site_url('agenda_surat_masuk/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-warning btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('tgl_terima', $q);
	$this->db->or_like('tgl_surat', $q);
	$this->db->or_like('no_surat', $q);
	$this->db->or_like('pengirim', $q);
	$this->db->or_like('perihal', $q);
	$this->db->or_like('diteruskan_kpd', $q);
	$this->db->or_like('kode_arsip', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('tgl_terima', $q);
	$this->db->or_like('tgl_surat', $q);
	$this->db->or_like('no_surat', $q);
	$this->db->or_like('pengirim', $q);
	$this->db->or_like('perihal', $q);
	$this->db->or_like('diteruskan_kpd', $q);
	$this->db->or_like('kode_arsip', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Agenda_surat_masuk_model.php */
/* Location: ./application/models/Agenda_surat_masuk_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-09-06 05:08:40 */
/* http://harviacode.com */