<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Info_hotel_model extends CI_Model
{

    public $table = 'info_hotel';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id,nama_hotel,jenis_kamar,tarif_kamar,fasilitas_hotel,sumber,namapimpinan');
        $this->datatables->from('v_info_hotel');
        //add this line for join
        //$this->datatables->join('table2', 'info_hotel.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('info_hotel/word/$1'),'<i class="fa fa-file-word-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm', 'target' => 'BLANK'))." 
                ".anchor(site_url('info_hotel/pdf/$1'),'<i class="fa fa-file-pdf-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm', 'target' => 'BLANK'))."    
                ".anchor(site_url('info_hotel/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('info_hotel/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get('v_info_hotel')->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('nama_hotel', $q);
	$this->db->or_like('jenis_kamar', $q);
	$this->db->or_like('tarif_kamar', $q);
	$this->db->or_like('fasilitas_hotel', $q);
	$this->db->or_like('sumber', $q);
	$this->db->or_like('pimpinan_id', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('nama_hotel', $q);
	$this->db->or_like('jenis_kamar', $q);
	$this->db->or_like('tarif_kamar', $q);
	$this->db->or_like('fasilitas_hotel', $q);
	$this->db->or_like('sumber', $q);
	$this->db->or_like('pimpinan_id', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Info_hotel_model.php */
/* Location: ./application/models/Info_hotel_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-09-14 06:48:51 */
/* http://harviacode.com */