<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Klasifikasi_arsip_model extends CI_Model
{

    public $table = 'klasifikasi_arsip';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id,indeks,kode_folder,kode_surat,masalah,keterangan');
        $this->datatables->from('klasifikasi_arsip');
        //add this line for join
        //$this->datatables->join('table2', 'klasifikasi_arsip.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('klasifikasi_arsip/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-warning btn-sm'))." 
                ".anchor(site_url('klasifikasi_arsip/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-warning btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by('kode_folder', 'ASC');
        return $this->db->get($this->table)->result();
    }

    function get_kode_surat()
    {
        $query = $this->db->query("SELECT * FROM klasifikasi_arsip WHERE kode_surat IS NOT NULL AND kode_surat !='' ORDER BY kode_folder");
        return $query->result();
    }
    

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('indeks', $q);
	$this->db->or_like('kode_folder', $q);
	$this->db->or_like('kode_surat', $q);
	$this->db->or_like('masalah', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('indeks', $q);
	$this->db->or_like('kode_folder', $q);
	$this->db->or_like('kode_surat', $q);
	$this->db->or_like('masalah', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Klasifikasi_arsip_model.php */
/* Location: ./application/models/Klasifikasi_arsip_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-09-06 08:04:52 */
/* http://harviacode.com */