<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pimpinan_model extends CI_Model
{

    public $table = 'pimpinan';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id,nama,tgl_keberangkatan,rute_keberangkatan,tgl_kepulangan,rute_kepulangan');
        $this->datatables->from('pimpinan');
        //add this line for join
        //$this->datatables->join('table2', 'pimpinan.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('pimpinan/infomaskapai/$1'),'<i class="fa fa-plane" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
        ".anchor(site_url('pimpinan/word/$1'),'<i class="fa fa-print" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm','target'=>'BLANK'))." 
            ".anchor(site_url('pimpinan/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('pimpinan/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get data by id
    function get_by_nama($nama)
    {
        $this->db->where('nama', $nama);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('tgl_keberangkatan', $q);
	$this->db->or_like('rute_keberangkatan', $q);
	$this->db->or_like('tgl_kepulangan', $q);
	$this->db->or_like('rute_kepulangan', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('tgl_keberangkatan', $q);
	$this->db->or_like('rute_keberangkatan', $q);
	$this->db->or_like('tgl_kepulangan', $q);
	$this->db->or_like('rute_kepulangan', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Pimpinan_model.php */
/* Location: ./application/models/Pimpinan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-09-14 07:53:15 */
/* http://harviacode.com */